export const state = {
  user: null,
  csrf: "",
  campuses: [],
  route: "/",
  type: "FOUND",
  filters: {
    status: "OPEN",
    campus_id: "",
    category: "",
    keyword: "",
    date_from: "",
    date_to: "",
  },
  homeLimit: 1,
  mineLimit: 1,
  conversationLimit: 1,
  unread: 0,
  posts: new Map(),
  mineType: "",
  mineStatus: "ALL",
  draft: null,
  dirty: false,
  uploading: false,
  pending: null,
  conversations: [],
  chat: null,
  messages: [],
  older: false,
  failed: null,
  renderId: 0,
  scrollHome: 0,
  chatDrafts: {},
};
