import crypto from "node:crypto";
import { now, today } from "../lib/validation.mjs";
const hash = (password, salt = crypto.randomBytes(16).toString("hex")) =>
  `${salt}:${crypto.scryptSync(password, salt, 64).toString("hex")}`;
export function seed() {
  const stamp = now();
  const users = [
    {
      id: "u-demo",
      account: "demo",
      nickname: "小杭",
      password_hash: hash("demo12345"),
      created_at: stamp,
    },
    {
      id: "u-ming",
      account: "xiaoming",
      nickname: "小明",
      password_hash: hash("demo12345"),
      created_at: stamp,
    },
  ];
  const items = [
    [
      "p-card",
      "FOUND",
      "黑色卡套校园卡",
      "CARD",
      "图书馆二楼",
      "黑色卡套，里面有一张校园卡。请说明卡套内的独有特征，核实后归还。",
      "card",
      "u-ming",
      "OPEN",
      "图书馆服务台",
    ],
    [
      "p-headphones",
      "FOUND",
      "白色无线耳机",
      "DIGITAL",
      "第三教学楼 302",
      "下课后在靠窗的座位捡到一副白色耳机，充电盒有一处小划痕。",
      "earbuds",
      "u-ming",
      "OPEN",
      "本人保管",
    ],
    [
      "p-keys",
      "FOUND",
      "带蓝色挂绳的一串钥匙",
      "KEY",
      "一食堂门口",
      "一串钥匙，带蓝色挂绳。请说明钥匙数量及挂件样式。",
      "keys",
      "u-ming",
      "OPEN",
      "",
    ],
    [
      "p-book",
      "FOUND",
      "《高等数学》课本",
      "BOOK",
      "第六教学楼",
      "捡到一本高等数学课本，内页有笔记，扉页有手写名字。",
      "book",
      "u-ming",
      "OPEN",
      "",
    ],
    [
      "p-bag",
      "LOST",
      "寻找米白色帆布包",
      "OTHER",
      "图书馆一楼",
      "米白色帆布包，里面有笔记本和水杯。如果有同学捡到，请站内联系我。",
      "bag",
      "u-demo",
      "OPEN",
      "",
    ],
    [
      "p-bottle",
      "LOST",
      "蓝色保温杯",
      "OTHER",
      "操场看台",
      "蓝色保温杯，杯盖上贴着小猫贴纸，昨天下午运动后遗失。",
      "bottle",
      "u-ming",
      "OPEN",
      "",
    ],
    [
      "p-mine",
      "FOUND",
      "黑色折叠雨伞",
      "OTHER",
      "二食堂",
      "黑色折叠伞，伞柄有一根灰色手绳，等失主来认领。",
      "umbrella",
      "u-demo",
      "OPEN",
      "本人保管",
    ],
    [
      "p-done",
      "LOST",
      "已经找回的学生证",
      "CARD",
      "教学楼",
      "学生证已经找回，感谢帮忙的同学。",
      "card",
      "u-demo",
      "RESOLVED",
      "",
    ],
  ];
  const posts = items.map((v, i) => ({
    id: v[0],
    type: v[1],
    title: v[2],
    category: v[3],
    campus_id: "xiasha",
    location: v[4],
    description: v[5],
    illustration: v[6],
    owner_id: v[7],
    status: v[8],
    storage_location: v[9],
    event_date: today(),
    event_period: i % 2 ? "上午" : "下午",
    image_ids: [],
    deleted_at: null,
    version: 1,
    created_at: new Date(Date.now() - i * 3600000).toISOString(),
    updated_at: stamp,
  }));
  const conversations = [
    {
      id: "c-demo",
      post_id: "p-card",
      initiator_id: "u-demo",
      owner_id: "u-ming",
      created_at: stamp,
      last_activity_at: stamp,
    },
  ];
  const messages = [
    {
      id: 1,
      conversation_id: "c-demo",
      sender_id: "u-demo",
      content: "你好，这张校园卡可能是我的，卡套里有一张蓝色贴纸。",
      client_message_id: "seed-1",
      created_at: stamp,
    },
    {
      id: 2,
      conversation_id: "c-demo",
      sender_id: "u-ming",
      content:
        "你好，特征一致！可以下午到图书馆服务台来取，记得带上能核实身份的信息。",
      client_message_id: "seed-2",
      created_at: stamp,
    },
  ];
  return {
    users,
    posts,
    images: [],
    conversations,
    messages,
    reads: [],
    idempotency: [],
    next_message_id: 3,
  };
}
